version: "3.9"

services:
  db-bank:
    image: mongo:6.0.2
    container_name: db-bank
    ports:
      - "${PORT}:27017"
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      # MONGO_INITDB_DATABASE:
      # MONGO_USERNAME:
      # MONGO_PASSWORD:
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
